name: "Master Build, Test & Deploy"

on:
  push:
    branches:
    - master
    - trigger-action

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install
      run: |
        npm install
        npm run setheapsize

    - name: Prepare for GitHub Pages
      if: success()
      run: npx grunt copy:ghPages

    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/master'
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        #build_dir: ./build/prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
